; --- การตั้งค่าส่วนกลาง (ใช้ร่วมกันทุก Environment) ---
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Library ที่ใช้เหมือนกันทั้งคู่ ใส่ตรงนี้ได้เลย (ประหยัดบรรทัด)
lib_deps_common =
    knolleary/PubSubClient @ ^2.8

; --- Node 1: Sensor Node ---
[env:node1_sensor]
; สำคัญ: -<*> คือ "ไม่เอาไฟล์ไหนเลย" แล้วค่อย +<...> คือ "เอาเฉพาะไฟล์นี้"
build_src_filter = -<*> +<node1_sensor.cpp>
lib_deps =
    ${env.lib_deps_common}      ; ดึง Library ส่วนกลางมาใช้
    claws/BH1750 @ ^1.3.0
    wifwaf/MH-Z19 @ ^1.5.4
    4-20ma/ModbusMaster @ ^2.0.1
    plerup/EspSoftwareSerial @ ^8.2.0

; --- Node 2: Relay Node ---
[env:node2_relay]
build_src_filter = -<*> +<node2_relay.cpp>
lib_deps =
    ${env.lib_deps_common}      ; ดึง Library ส่วนกลางมาใช้
    bblanchon/ArduinoJs